In [1]:
import pandas as pd
import json
import numpy
from splinter import Browser
from bs4 import BeautifulSoup
import requests

In [2]:
golf_data = pd.read_csv("data (version 1).csv")
golf_data

,Name,SG: Total,SG: Tee-to-Green,SG: Off-the-Tee,SG: Approach the Green,SG: Around-the-Green,SG: Putting,Total Driving,Ball Striking,Longest Drives,...,Unnamed: 382,Unnamed: 383,Unnamed: 384,Unnamed: 385,Unnamed: 386,Unnamed: 387,Unnamed: 388,Unnamed: 389,Unnamed: 390,Unnamed: 391
0,Jon Rahm,2.528,1.722,0.392,0.959,0.371,0.806,127.0,23.0,415.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Max Homa,2.179,1.380,0.208,0.911,0.261,0.799,116.0,68.0,419.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Tony Finau,2.158,1.663,0.503,1.056,0.104,0.495,162.0,62.0,397.0,...,-0.571,32.0,4.61,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Rory McIlroy,1.989,2.280,0.800,0.894,0.585,-0.290,184.0,199.0,388.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Scottie Scheffler,1.970,1.956,0.963,0.785,0.208,0.014,73.0,7.0,451.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1614,Calum Fyfe,0.090,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1615,Yuki Usami,0.090,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1616,Marco Iten,0.090,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1617,Ryo Noro,0.090,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1618,Max Rottluff,0.090,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:

golf_data = golf_data.loc[:, ["Name", "Driving Distance", "Driving Accuracy Percentage", "Greens in Regulation Percentage", 
                             "Putts Per Round", "Rough Tendency", "Scrambling", "Proximity to Hole", "Approaches from inside 100 yards", 
                             "Approaches from > 100 yards", "Sand Save Percentage"]]
golf_data

,Name,Driving Distance,Driving Accuracy Percentage,Greens in Regulation Percentage,Putts Per Round,Rough Tendency,Scrambling,Proximity to Hole,Approaches from inside 100 yards,Approaches from > 100 yards,Sand Save Percentage
0,Jon Rahm,314.2,57.32,73.02,28.00,30.88,63.24,35.333333,17.833333,30.166667,51.52
1,Max Homa,303.5,61.95,68.75,27.72,25.75,68.89,36.666667,15.333333,31.250000,52.94
2,Tony Finau,303.0,58.81,70.93,28.47,29.68,68.15,36.333333,17.166667,32.000000,59.46
3,Rory McIlroy,327.6,52.68,65.97,27.00,31.36,67.35,38.416667,14.750000,33.083333,60.00
4,Scottie Scheffler,309.1,62.72,73.61,28.50,27.98,67.76,38.666667,14.000000,34.000000,39.13
...,...,...,...,...,...,...,...,...,...,...,...
1614,Calum Fyfe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1615,Yuki Usami,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1616,Marco Iten,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1617,Ryo Noro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1618,Max Rottluff,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
url = 'https://www.espn.com/golf/rankings'

# Use pandas to read the table on the page
dfs = pd.read_html(url)

# Select the first table, which contains the world golf rankings
world_rankings = dfs[0]

# Display the rankings
world_rankings = world_rankings.rename(columns={'NAME': 'Name'})
world_rankings

      RK               Name
0      1           Jon Rahm
1      2  Scottie Scheffler
2      3       Rory McIlroy
3      4    Patrick Cantlay
4      5      Cameron Smith
..   ...                ...
195  196   Charl Schwartzel
196  197       Kaito Onishi
197  198           Chan Kim
198  199         Ben Martin
199  199      Matthew Wolff

[200 rows x 2 columns]

In [5]:
merged_df = pd.merge(golf_data, world_rankings, on='Name')
merged_df

,Name,Driving Distance,Driving Accuracy Percentage,Greens in Regulation Percentage,Putts Per Round,Rough Tendency,Scrambling,Proximity to Hole,Approaches from inside 100 yards,Approaches from > 100 yards,Sand Save Percentage,RK
0,Jon Rahm,314.2,57.32,73.02,28.00,30.88,63.24,35.333333,17.833333,30.166667,51.52,1
1,Max Homa,303.5,61.95,68.75,27.72,25.75,68.89,36.666667,15.333333,31.250000,52.94,7
2,Tony Finau,303.0,58.81,70.93,28.47,29.68,68.15,36.333333,17.166667,32.000000,59.46,14
3,Rory McIlroy,327.6,52.68,65.97,27.00,31.36,67.35,38.416667,14.750000,33.083333,60.00,3
4,Scottie Scheffler,309.1,62.72,73.61,28.50,27.98,67.76,38.666667,14.000000,34.000000,39.13,2
...,...,...,...,...,...,...,...,...,...,...,...,...
187,Callum Shinkwin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92
188,Ewen Ferguson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,137
189,Oliver Bekker,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,117
190,Daniel Gavins,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,184
191,Phachara Khongwatmai,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,194

In [6]:
merged_df = merged_df.dropna()
merged_df

,Name,Driving Distance,Driving Accuracy Percentage,Greens in Regulation Percentage,Putts Per Round,Rough Tendency,Scrambling,Proximity to Hole,Approaches from inside 100 yards,Approaches from > 100 yards,Sand Save Percentage,RK
0,Jon Rahm,314.2,57.32,73.02,28.00,30.88,63.24,35.333333,17.833333,30.166667,51.520000,1
1,Max Homa,303.5,61.95,68.75,27.72,25.75,68.89,36.666667,15.333333,31.250000,52.940000,7
2,Tony Finau,303.0,58.81,70.93,28.47,29.68,68.15,36.333333,17.166667,32.000000,59.460000,14
3,Rory McIlroy,327.6,52.68,65.97,27.00,31.36,67.35,38.416667,14.750000,33.083333,60.000000,3
4,Scottie Scheffler,309.1,62.72,73.61,28.50,27.98,67.76,38.666667,14.000000,34.000000,39.130000,2
...,...,...,...,...,...,...,...,...,...,...,...,...
111,MJ Daffue,306.3,56.43,67.70,29.38,30.55,54.44,35.833333,18.833333,33.250000,64.710000,147
112,Lucas Glover,290.3,65.32,65.28,27.40,25.09,58.11,35.333333,14.083333,34.083333,100.000000,132
113,Kevin Kisner,280.8,59.76,60.19,0.50,23.92,48.00,40.583333,19.083333,39.333333,4.583333,53
114,John Huh,285.5,57.27,61.34,27.50,28.99,52.63,40.583333,15.166667,38.833333,16.670000,180
115,Chez Reavie,286.8,66.74,67.53,30.38,24.58,57.22,38.250000,20.916667,34.916667,45.650000,134

In [7]:
top_10 = merged_df[(merged_df['RK'] >= 1) & (merged_df['RK'] <= 10)]
averages_top_10 = top_10.mean()
averages_top_10

Driving Distance                    310.566667
Driving Accuracy Percentage          59.014444
Greens in Regulation Percentage      69.670000
Putts Per Round                      28.175556
Rough Tendency                       30.151111
Scrambling                           64.991111
Proximity to Hole                    37.935185
Approaches from inside 100 yards     15.824074
Approaches from > 100 yards          33.564815
Sand Save Percentage                 54.772222
RK                                    5.555556
dtype: float64

In [8]:
next_11_25 = merged_df[(merged_df['RK'] >= 11) & (merged_df['RK'] <= 25)]
averages_11_25 = next_11_25.mean()
averages_11_25

Driving Distance                    303.157143
Driving Accuracy Percentage          60.345000
Greens in Regulation Percentage      67.684286
Putts Per Round                      27.655000
Rough Tendency                       26.939286
Scrambling                           61.532143
Proximity to Hole                    38.386905
Approaches from inside 100 yards     18.160714
Approaches from > 100 yards          33.619048
Sand Save Percentage                 48.402857
RK                                   17.571429
dtype: float64

In [9]:
next_26_50 = merged_df[(merged_df['RK'] >= 26) & (merged_df['RK'] <= 50)]
averages_26_50 = next_26_50.mean()
averages_26_50

Driving Distance                    298.215789
Driving Accuracy Percentage          61.703684
Greens in Regulation Percentage      68.733684
Putts Per Round                      28.860000
Rough Tendency                       27.306842
Scrambling                           61.113684
Proximity to Hole                    38.197368
Approaches from inside 100 yards     16.938596
Approaches from > 100 yards          34.548246
Sand Save Percentage                 51.117895
RK                                   37.526316
dtype: float64

In [10]:
next_51_100 = merged_df[(merged_df['RK'] >= 51) & (merged_df['RK'] <= 100)]
averages_51_100 = next_51_100.mean()
averages_51_100

Driving Distance                    299.550000
Driving Accuracy Percentage          58.315667
Greens in Regulation Percentage      67.146667
Putts Per Round                      27.810333
Rough Tendency                       30.519000
Scrambling                           62.840000
Proximity to Hole                    38.250000
Approaches from inside 100 yards     17.941667
Approaches from > 100 yards          34.358333
Sand Save Percentage                 51.857111
RK                                   73.133333
dtype: float64

In [11]:
over_100 = merged_df[(merged_df['RK'] >= 101)]
averages_over_100 = over_100.mean()
averages_over_100

Driving Distance                    298.202273
Driving Accuracy Percentage          58.682273
Greens in Regulation Percentage      67.357273
Putts Per Round                      29.058182
Rough Tendency                       31.394545
Scrambling                           58.907273
Proximity to Hole                    37.729167
Approaches from inside 100 yards     17.308712
Approaches from > 100 yards          33.926136
Sand Save Percentage                 51.061364
RK                                  142.409091
dtype: float64

In [12]:
all_averages = pd.concat([averages_top_10, averages_11_25, averages_26_50, averages_51_100, averages_over_100], axis = 1)
all_averages.columns = ["Top Ten", "11-25", "26-50", "51-100", "Over 100"]
all_averages

,Top Ten,11-25,26-50,51-100,Over 100
Driving Distance,310.566667,303.157143,298.215789,299.550000,298.202273
Driving Accuracy Percentage,59.014444,60.345000,61.703684,58.315667,58.682273
Greens in Regulation Percentage,69.670000,67.684286,68.733684,67.146667,67.357273
Putts Per Round,28.175556,27.655000,28.860000,27.810333,29.058182
Rough Tendency,30.151111,26.939286,27.306842,30.519000,31.394545
Scrambling,64.991111,61.532143,61.113684,62.840000,58.907273
Proximity to Hole,37.935185,38.386905,38.197368,38.250000,37.729167
Approaches from inside 100 yards,15.824074,18.160714,16.938596,17.941667,17.308712
Approaches from > 100 yards,33.564815,33.619048,34.548246,34.358333,33.926136
Sand Save Percentage,54.772222,48.402857,51.117895,51.857111,51.061364
RK,5.555556,17.571429,37.526316,73.133333,142.409091

In [14]:
merged_df.to_json('merged_golf_data.json', orient='records')

In [14]:
merged_df.to_json('test_golf_data.json')